2022-11-09 16:01:31,801 INFO An INFO
2022-11-09 16:01:31,801 WARNING A WARNING
2022-11-09 16:01:31,801 ERROR An ERROR
2022-11-09 16:01:31,802 CRITICAL A message of CRITICAL severity
2022-11-09 16:10:21,906 INFO The values of x and y are 3 and 2.
2022-11-09 16:10:21,906 INFO x / y successful with result: 1.5.
2022-11-09 16:10:50,899 INFO The values of x and y are 3 and 0.
2022-11-09 16:10:50,900 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "C:\Users\theba\AppData\Local\Temp\ipykernel_9936\3515123034.py", line 6, in <module>
    x / y
    ~~^~~
ZeroDivisionError: division by zero
2022-11-09 16:11:29,702 INFO The values of x and y are 3 and 0.
2022-11-09 16:11:29,703 ERROR ZeroDivisionError
2022-11-09 16:11:53,866 INFO The values of x and y are 2 and 5.
2022-11-09 16:11:53,866 INFO x / y successful with result: 0.4.
2022-11-09 16:11:53,866 INFO The values of x and y are 3 and 7.
2022-11-09 16:11:53,866 INFO x / y successful with result: 0.42857142857142855.
2022-11-09 16:11:53,866 INFO The values of x and y are 6 and 12.
2022-11-09 16:11:53,866 INFO x / y successful with result: 0.5.
2022-11-09 16:11:53,866 INFO The values of x and y are 4 and 0.
2022-11-09 16:11:53,866 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "C:\Users\theba\AppData\Local\Temp\ipykernel_9936\3070704183.py", line 8, in <module>
    x / y
    ~~^~~
ZeroDivisionError: division by zero
2022-11-09 16:11:53,867 INFO The values of x and y are 10 and 1.
2022-11-09 16:11:53,867 INFO x / y successful with result: 10.0.
2022-11-09 16:14:02,015 INFO Testing the custom logger for module __main__...
2022-11-09 16:14:30,543 INFO Testing the custom logger for module __main__...
2022-11-09 16:14:30,543 INFO x / y successful with result: 0.4.
2022-11-09 16:14:30,543 INFO Call test_division with args 2 and 5
2022-11-09 16:14:30,544 INFO x / y successful with result: 0.42857142857142855.
2022-11-09 16:14:30,544 INFO Call test_division with args 3 and 7
2022-11-09 16:14:30,544 INFO x / y successful with result: 0.5.
2022-11-09 16:14:30,544 INFO Call test_division with args 6 and 12
2022-11-09 16:14:30,545 ERROR ZeroDivisionError
Traceback (most recent call last):
  File "C:\Users\theba\AppData\Local\Temp\ipykernel_9936\2572795720.py", line 6, in test_division
    x / y
    ~~^~~
ZeroDivisionError: division by zero
2022-11-09 16:14:30,547 INFO Call test_division with args 4 and 0
2022-11-09 16:14:30,548 INFO x / y successful with result: 10.0.
2022-11-09 16:14:30,548 INFO Call test_division with args 10 and 1
